version: '3.8'

services:
    postgesql:
        image: postgres:12-alpine
        container_name: postgres12
        ports:
            - '5432:5432'
        restart: always
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
        networks:
            - web_api

networks:
    web_api:
        driver: bridge
